### ISSUE TITLE
Include File.description in J10P submission metadata

### ISSUE THREAD

**Issue by emetsger** [eclipse-pass/pass-deposit-services#128]
Submission: https://pass.jhu.edu/fcrepo/rest/submissions/66/91/f5/7f/6691f57f-ab68-4daa-8043-b4a2bccadcd3
File: https://pass.jhu.edu/fcrepo/rest/files/40/ec/56/d2/40ec56d2-abc3-4c7d-8b44-1117a7eb1b6f
J10S: https://jscholarship.library.jhu.edu/handle/1774.2/59078

**Comment by emetsger** [comment]
Reviewed 1/7/19: The File.description is copied into the DepositFile.label, but DepositFile.label is not used by the DSpace/J10P packager.

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete. This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
