### ISSUE TITLE
Analyze the requirements for the Deposit Remediation tool and design its implementation at a high level

### ISSUE THREAD

**Issue by htpvu** [eclipse-pass/pass-deposit-services#146]
Expected out come:

- description of the tool's purpose and the problem it'll be used to address
- enumerate its components and specify its interaction with existing components in PASS (what resources does it act on, using which criteria, how does it communicate with other things)
- enumerate list of tasks that will need to be done in order to implement this tool. (as high/low of a level as you can. we'll follow up when i get back)

**Comment by emetsger** [comment]
Currently envision a dashboard written as an Ember app that communicates with Elastic Search for building out the dashboard.  Provides the ability to list all `Deposit` resources, and associated Submission metadata, and order and filter them by certain criteria (such as deposit status or date).

Deposit services will need to implement and expose a service that allows a user of the Deposit Dashboard to (force) re-try a Deposit.

Ideally this dashboard could be used by interested parties (IRD, system admins, end user support) to see incoming Deposits, their status, and force a retry of a failed deposit if necessary.

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete. This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
