### ISSUE TITLE
Update the Transport API to expose deposit status and polling semantics

### ISSUE THREAD

**Issue by emetsger** [eclipse-pass/pass-deposit-services#196]
The abstraction presented by the Transport API breaks down in `DepositTask` where there is [conditional handling](https://github.com/OA-PASS/deposit-services/blob/master/deposit-messaging/src/main/java/org/dataconservancy/pass/deposit/messaging/service/DepositTask.java#L182) of the concrete `Sword2DepositReceiptResponse`.

The Transport API needs to be updated to encapsulate the logic to be executed when a `TransportResponse` results in the creation of a deposit status reference that may be polled for logical success of the `Deposit`.

Some ideas include some form of callback invoked by DS on the `TransportResponse` like:
- `void onSuccess(Deposit, RepositoryCopy)` or
- `void onSuccess(RepositoryCopy)`

Open questions are:
- Who is responsible for updating the `Deposit.depositStatusRef`?  Should the `TransportResponse` expose the URI and have the `DepositTask` be responsible for the update?
- Who creates the `RepositoryCopy`: the `DepositTask` or the `TransportResponse`?

This issue will need to be resolved to create a more proper test suite for `PackageProvider`s.  There are ITs in the core DS codebase that rely on, or expect, the `Sword2Transport` to be used (i.e. any IT that requires JScholarship such as `DepositProcessorIT`, `SubmissionProcessorIT`, or `SubmittedStatusHandlingIT`).  Ideally, the transports ought to be tested independent of any specific implementation, but that is challenging to do at the moment because of how `DepositTask` conditionally handles the `Sword2DepositReceiptResponse`.

**Comment by emetsger** [comment]
This would have the nice side effect of moving the JScholarship SWORD URL hack out of `DepositTask`.

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete. This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
