### ISSUE TITLE
Investigate switch to Java 11

### ISSUE THREAD

**Issue by emetsger** [eclipse-pass/pass-deposit-services#238]
Notes on a brief attempt to upgrade Deposit Services to Java 11.  

- Installing Java 11 JDK locally and attempting to build with `<target>` and `<source>` of 1.8 failed with a javadoc generation error.  This was with an up-to-date Maven javadoc and compiler plugin.
- Building with `<target>` and `<source>` of 11 seemed to work, however, there is no JDK 11 Alpine image.  The latest Alpine package for the JDK is JDK 10, so you can't even build your own image from the Alpine distribution package.

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete. This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
