### ISSUE TITLE
Clean up depedencies

### ISSUE THREAD

**Issue by emetsger** [eclipse-pass/pass-deposit-services#249]
Jackson 2.9.6 and 2.9.8 are present in BOOT-INF/lib
commons-lang-1.0 and commons-lang3-3.8.1 are present in BOOT-INF/lib
geronimo-activation_1.0.2_spec-1.1 and geronimo-activation_1.1_spec-1.0.2 are both present in BOOT-INF/lib

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete. This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
