### ISSUE TITLE
Update AuthenticatedResource to follow HTTP redirects

### ISSUE THREAD

**Issue by emetsger** [eclipse-pass/pass-deposit-services#262]
The Spring Resource framework is an abstraction for obtaining an `InputStream`, regardless of where the bytes come from.  Implementations of a Spring `Resource` include: `FileResource`, `JarResource`, `ClassPathResource`, `ServletContextResource`, etc.

`AuthenticatedResource` is a PASS-specific `Resource` implementation extending the Spring `UrlResource`.  `AuthenticatedResource` preemptively supplies Basic authentication credentials when performing HTTP GET.

This PR updates the underlying `URLConnection` of the `AuthenticatedResource` to follow HTTP  redirects.

**Comment by rpoet-jh** [comment]
The migration of PASS repositories to eclipse-pass is complete. This issue is no longer relevant and is being closed as part of archiving https://github.com/eclipse-pass/main/issues/585.
